# Base Ruby layer
FROM ruby:2.3.0

# Add system libraries layer
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs libleptonica-dev libtesseract-dev

# Create directory for tesseract and fetch training data
RUN mkdir /usr/local/share/tessdata
RUN curl -L https://github.com/danReynolds/ruby-tesseract-ocr/raw/master/eng.traineddata > /usr/local/share/tessdata/eng.traineddata
