source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'mysql2'
gem 'haml-rails'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'simple_form'
gem 'foundation-rails'
gem 'sorcery'
gem 'select2-rails'
gem 'jquery-datatables-rails', '~> 3.1.1'
gem 'font-awesome-rails'
gem 'groupdate'
gem 'chartkick'
gem 'happy_path'
gem 'money-rails'
gem 'canard', '0.4.2.pre'
gem 'capistrano',  '~> 3.1'
gem 'capistrano-rails', '~> 1.1'

group :development do
  gem 'pry'
  gem 'pry-stack_explorer'
	gem 'spring'
	gem 'better_errors'
	gem 'binding_of_caller'
end
